<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Infrangible\RetailStore\Block\Widget\GoogleMaps\Search\Buttons;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Buttons $block */

/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);
?>

<button type="submit"
        id="location-search"
        name="location-search"
        title="<?= $escaper->escapeHtmlAttr(__('Search Retail Store')); ?>"
        class="btn btn-primary">
    <?= $heroIcons->searchHtml('border-current'); ?>
    <span class="hidden sm:block md:hidden lg:block"><?= $escaper->escapeHtml(__('Search Retail Store')); ?></span>
</button>

<button type="button"
        id="determine-location"
        name="determine-location"
        title="<?= $escaper->escapeHtmlAttr(__('Determine location')); ?>"
        class="btn btn-secondary">
    <?= $heroIcons->locationMarkerHtml('border-current'); ?>
    <span class="hidden sm:block md:hidden lg:block"><?= $escaper->escapeHtml(__('Determine location')); ?></span>
</button>
